get https://localhost:5001/api/inquilinos HTTP/1.1
content-type: application/json

###

get https://localhost:44328/api/imoveis HTTP/1.1
content-type: application/json
###

get https://localhost:44328/api/imoveis/4 HTTP/1.1
content-type: application/json
###

get https://localhost:44328/api/contratosAluguel?imovelId=14 HTTP/1.1
content-type: application/json
###

put  https://localhost:44328/api/ContratosAluguel/21/reajusta HTTP/1.1
content-type: application/json

{"Data": "2022-02-01", "valorAluguel": 2200}
###
post  https://localhost:44328/api/ContratosAluguel HTTP/1.1
content-type: application/json

{
  "DataInicio":"2022-02-21",
  "ValorAluguel": 3000,
  "TaxaAdministracao": 10,
  "ImovelId": 26,
  "InquilinoId": 25 
}

###
put  https://localhost:44328/api/ContratosAluguel/27/assina HTTP/1.1
content-type: application/json

###
put  https://localhost:44328/api/ContratosAluguel/1/encerra HTTP/1.1
content-type: application/json

{"Data": "2022-02-01"}

###
put  https://localhost:44328/api/ContratosAluguel/19/posterga HTTP/1.1
content-type: application/json

###
get  https://localhost:44328/api/ContratosAluguel/ListaMovimentacaoMensal?ano=2022&mes=03 HTTP/1.1
content-type: application/json

###
post  https://localhost:44328/api/ContratosAluguel HTTP/1.1
content-type: application/json

{
  "DataInicio":"2022-02-21",
  "ValorAluguel": 3000,
  "TaxaAdministracao": 10,
  "ImovelId": 26,
  "InquilinoId": 25 
}

###
put  https://localhost:44328/api/ContratosAluguel/13/Reajusta HTTP/1.1
content-type: application/json

{
  "Data":"2022-03-01",
  "ValorAluguel": 600
}